apiVersion: apps/v1
kind: Deployment
metadata:
  name: openntf-todo-mongo-service-deployment
  labels:
    app: openntf-todo-mongo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openntf-todo-mongo-service
  template:
    metadata:
      labels:
        app: openntf-todo-mongo-service
    spec:
      containers:
      - name: openntf-todo-mongo-service
        image: registry.ng.bluemix.net/openntf/openntf-todo-mongo-service:latest
        ports:
        - containerPort: 8089

---
kind: Service
apiVersion: v1
metadata:
  name: openntf-todo-mongo-service-deployment
spec:
  selector:
    app: openntf-todo-mongo-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8089